"""add tags, categories and asset tag join

Revision ID: e50ff6692da7
Revises: 584b2e6c9e00
Create Date: 2026-09-13 16:32:12.298333+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'e50ff6692da7'
down_revision: Union[str, None] = '584b2e6c9e00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tag_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tag_user_id'), ['user_id'], unique=False)

    # Written by hand: autogenerate does not emit expression indexes. It produced the two
    # plain indexes above and silently dropped this one, which is the entire
    # case-insensitivity guarantee — without it "NATO" and "nato" both insert and the
    # library quietly splits in two. `tests/test_tags.py` asserts it exists in a migrated
    # database rather than in the model metadata, because metadata is what lied here.
    op.execute("CREATE UNIQUE INDEX ux_tag_user_lower_name ON tag (user_id, lower(name))")

    op.create_table('tagcategory',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_category_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tagcategory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tagcategory_parent_category_id'), ['parent_category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tagcategory_user_id'), ['user_id'], unique=False)

    op.create_table('assettag',
    sa.Column('asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tag_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('asset_id', 'tag_id')
    )
    with op.batch_alter_table('assettag', schema=None) as batch_op:
        batch_op.create_index('ix_assettag_tag', ['tag_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assettag', schema=None) as batch_op:
        batch_op.drop_index('ix_assettag_tag')

    op.drop_table('assettag')
    with op.batch_alter_table('tagcategory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tagcategory_user_id'))
        batch_op.drop_index(batch_op.f('ix_tagcategory_parent_category_id'))

    op.drop_table('tagcategory')
    op.execute("DROP INDEX IF EXISTS ux_tag_user_lower_name")
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_user_id'))
        batch_op.drop_index(batch_op.f('ix_tag_category_id'))

    op.drop_table('tag')
    # ### end Alembic commands ###
