"""allow library wide jobs

A backfill embeds the whole library, so its job row is about no single asset. Every
other kind is per-asset, which is why the column was NOT NULL to begin with.

Revision ID: 997f000122a7
Revises: e50ff6692da7
Create Date: 2026-09-14 12:16:57.392716+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '997f000122a7'
down_revision: Union[str, None] = 'e50ff6692da7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrichmentjob', schema=None) as batch_op:
        batch_op.alter_column('asset_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # Clear the rows this migration made possible before restoring NOT NULL. On SQLite
    # batch_alter_table rebuilds the table and copies the rows in, so a surviving NULL
    # fails the rebuild and the downgrade dies halfway.
    #
    # Deleting them is the right call rather than inventing an asset_id: they are job
    # history for a kind the downgraded code cannot run, and a fabricated id would leave
    # the activity feed rendering rows that resolve to an asset that was never involved.
    # What is lost is a log line.
    op.execute("DELETE FROM enrichmentjob WHERE asset_id IS NULL")

    with op.batch_alter_table('enrichmentjob', schema=None) as batch_op:
        batch_op.alter_column('asset_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
